# DATA PREPROCESSING IN TRAIN SET

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from pprint import pprint

In [2]:
import pandas as pd
df=pd.read_csv("C:/datasets/train.csv")
df

     PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0              1         0       3    male  22.0      1      0   7.2500
1              2         1       1  female  38.0      1      0  71.2833
2              3         1       3  female  26.0      0      0   7.9250
3              4         1       1  female  35.0      1      0  53.1000
4              5         0       3    male  35.0      0      0   8.0500
..           ...       ...     ...     ...   ...    ...    ...      ...
615          616         1       2  female  24.0      1      2  65.0000
616          617         0       3    male  34.0      1      1  14.4000
617          618         0       3  female  26.0      1      0  16.1000
618          619         1       2  female   4.0      2      1  39.0000
619          620         0       2    male  26.0      0      0  10.5000

[620 rows x 8 columns]

In [3]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,620.000000,620.000000,620.000000,489.000000,620.000000,620.000000,620.000000
mean,310.500000,0.393548,2.309677,29.781186,0.538710,0.382258,31.746982
std,179.122863,0.488931,0.833993,14.404998,1.086018,0.792131,45.907139
min,1.000000,0.000000,1.000000,0.750000,0.000000,0.000000,0.000000
25%,155.750000,0.000000,2.000000,21.000000,0.000000,0.000000,7.925000
50%,310.500000,0.000000,3.000000,28.000000,0.000000,0.000000,14.750000
75%,465.250000,1.000000,3.000000,38.000000,1.000000,0.000000,30.548950
max,620.000000,1.000000,3.000000,71.000000,8.000000,5.000000,512.329200

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620 entries, 0 to 619
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  620 non-null    int64
 1   Survived     620 non-null    int64
 2   Pclass       620 non-null    int64
 3   Sex          620 non-null    object
 4   Age          489 non-null    float64
 5   SibSp        620 non-null    int64
 6   Parch        620 non-null    int64
 7   Fare         620 non-null    float64
dtypes: float64(2), int64(5), object(1)
memory usage: 38.9+ KB

In [5]:
df["Age"].count()

489

In [6]:
df["Age"].isnull().sum()

131

In [7]:
df["Age"].fillna(method="ffill",inplace=True)

In [8]:
df["Age"].isnull().sum()

0

# DATA PREPROCESSING IN TEST SET

In [9]:
df1=pd.read_csv("C:/datasets/test.csv")
df1

     PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0            621         0       3    male  27.0      1      0  14.4542
1            622         1       1    male  42.0      1      0  52.5542
2            623         1       3    male  20.0      1      1  15.7417
3            624         0       3    male  21.0      0      0   7.8542
4            625         0       3    male  21.0      0      0  16.1000
..           ...       ...     ...     ...   ...    ...    ...      ...
266          887         0       2    male  27.0      0      0  13.0000
267          888         1       1  female  19.0      0      0  30.0000
268          889         0       3  female   NaN      1      2  23.4500
269          890         1       1    male  26.0      0      0  30.0000
270          891         0       3    male  32.0      0      0   7.7500

[271 rows x 8 columns]

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  271 non-null    int64
 1   Survived     271 non-null    int64
 2   Pclass       271 non-null    int64
 3   Sex          271 non-null    object
 4   Age          225 non-null    float64
 5   SibSp        271 non-null    int64
 6   Parch        271 non-null    int64
 7   Fare         271 non-null    float64
dtypes: float64(2), int64(5), object(1)
memory usage: 17.1+ KB

In [11]:
df1.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,271.000000,271.000000,271.000000,225.000000,271.000000,271.000000,271.000000
mean,756.000000,0.361624,2.306273,29.520756,0.487085,0.380074,33.250261
std,78.375166,0.481360,0.842350,14.817980,1.141320,0.838545,57.505283
min,621.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,688.500000,0.000000,2.000000,20.000000,0.000000,0.000000,7.895800
50%,756.000000,0.000000,3.000000,28.000000,0.000000,0.000000,13.000000
75%,823.500000,1.000000,3.000000,39.000000,1.000000,0.000000,31.797900
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [12]:
df1["Age"].isnull().sum()

46

In [13]:
df1["Age"].fillna(method="ffill",inplace=True)

In [14]:
df1["Age"].isnull().sum()

0

# BUILDING MODEL IN DECISION TREE

In [15]:
###defining entropy
def entropy(target_col):
    elements,counts = np.unique(target_col,return_counts=True)
    entropy = np.sum([(-counts[i]/np.sum(counts))*np.log2(counts[i]/np.sum(counts)) for i in range(len(elements))])
    return entropy
  
##Info Gain

def InfoGain(data,split_attribute_name,target_name="Survived"):
    total_entropy = entropy(data[target_name])
    vals,counts = np.unique(data[split_attribute_name],return_counts=True)
    #cal the weighted entropy
    Weighted_Entropy = np.sum([(counts[i]/np.sum(counts))*entropy(data.where(data[split_attribute_name]==vals[i]).
                                dropna()[target_name])for i in range(len(vals))])
    
    #formula for information gain
    Information_Gain = total_entropy-Weighted_Entropy
    return Information_Gain

def ID3(data,originaldata,features,target_attribute_name="Survived",
        parent_node_class=None):
    #If all target_values have the same value,return this value
    if len(np.unique(data[target_attribute_name])) <= 1:
        return np.unique(data[target_attribute_name])[0]
    
    #if the dataset is empty
    elif len(data) == 0:
        return np.unique(originaldata[target_attribute_name])[np.argmax(np.unique(originaldata[target_attribute_name],
                                                                           return_counts=True)[1])]
    
    #If the feature space is empty
    elif len(features) == 0:
        return parent_node_class 

    #If none of the above condition holds true grow the tree

    else:
        parent_node_class = np.unique(data[target_attribute_name])[np.argmax(np.unique(data[target_attribute_name],
                                                                           return_counts=True)[1])]

    #Select the feature which best splits the dataset
    item_values = [InfoGain(data,feature,target_attribute_name)for feature in features] #Return the infgain values
    best_feature_index = np.argmax(item_values)
    best_feature = features[best_feature_index]

    #Create the tree structure
    tree = {best_feature:{}}

    #Remve the feature with the best info gain
    features = [i for i in features if i!= best_feature]

    #Grow the tree branch under the root node

    for value in np.unique(data[best_feature]):
        value = value
        sub_data = data.where(data[best_feature]==value).dropna()
        #call the ID3 algotirthm
        subtree = ID3(sub_data,df,features,target_attribute_name,parent_node_class)
        #Add the subtree
        tree[best_feature][value] = subtree
    return(tree)

#Predict
def predict(query,tree,default=1):
    for key in list(query.keys()):
        if key in list(tree.keys()):
            try:
               result = tree[key][query[key]]
            except:
               return default

            result = tree[key][query[key]]
            if isinstance(result,dict):
                return predict(query,result)
            else:
                return result
##check the accuracy

def train_test_split(dataset):
    training_data = df.iloc[:620].reset_index(drop=True)
    testing_data = df1.iloc[:270].reset_index(drop=True)
    return training_data,testing_data
training_data = train_test_split(df)[0]
testing_data = train_test_split(df1)[1]

def test(data,tree):
   queries = data.iloc[:,1:2].to_dict(orient="records")
   predicted = pd.DataFrame(columns=["predicted"])

   #calculation of accuracy

   for i in range(len(data)):
       predicted.loc[i,"predicted"] = predict(queries[i],tree,1.0)
       print("The Prediction accuracy is:",(np.sum(predicted["predicted"]==data["Survived"])/len(data))*100,'%')
  
#Train the tree,print the tree abnd predict the accuracy
tree = ID3(training_data,training_data,training_data.columns[:-1])
pprint(tree)
test(testing_data,tree)

{'PassengerId': {1: 0.0,
                 2: 1.0,
                 3: 1.0,
                 4: 1.0,
                 5: 0.0,
                 6: 0.0,
                 7: 0.0,
                 8: 0.0,
                 9: 1.0,
                 10: 1.0,
                 11: 1.0,
                 12: 1.0,
                 13: 0.0,
                 14: 0.0,
                 15: 0.0,
                 16: 1.0,
                 17: 0.0,
                 18: 1.0,
                 19: 0.0,
                 20: 1.0,
                 21: 0.0,
                 22: 1.0,
                 23: 1.0,
                 24: 1.0,
                 25: 0.0,
                 26: 1.0,
                 27: 0.0,
                 28: 0.0,
                 29: 1.0,
                 30: 0.0,
                 31: 0.0,
                 32: 1.0,
                 33: 1.0,
                 34: 0.0,
                 35: 0.0,
                 36: 0.0,
                 37: 1.0,
                 38: 0.0,
                 39: 0.0,
                 40: 1.0,
                 41: 0.0,
                 42: 0.0,
                 43: 0.0,
                 44: 1.0,
                 45: 1.0,
                 46: 0.0,
                 47: 0.0,
                 48: 1.0,
                 49: 0.0,
                 50: 0.0,
                 51: 0.0,
                 52: 0.0,
                 53: 1.0,
                 54: 1.0,
                 55: 0.0,
                 56: 1.0,
                 57: 1.0,
                 58: 0.0,
                 59: 1.0,
                 60: 0.0,
                 61: 0.0,
                 62: 1.0,
                 63: 0.0,
                 64: 0.0,
                 65: 0.0,
                 66: 1.0,
                 67: 1.0,
                 68: 0.0,
                 69: 1.0,
                 70: 0.0,
                 71: 0.0,
                 72: 0.0,
                 73: 0.0,
                 74: 0.0,
                 75: 1.0,
                 76: 0.0,
                 77: 0.0,
                 78: 0.0,
                 79: 1.0,
                 80: 1.0,
                 81: 0.0,
                 82: 1.0,
                 83: 1.0,
                 84: 0.0,
                 85: 1.0,
                 86: 1.0,
                 87: 0.0,
                 88: 0.0,
                 89: 1.0,
                 90: 0.0,
                 91: 0.0,
                 92: 0.0,
                 93: 0.0,
                 94: 0.0,
                 95: 0.0,
                 96: 0.0,
                 97: 0.0,
                 98: 1.0,
                 99: 1.0,
                 100: 0.0,
                 101: 0.0,
                 102: 0.0,
                 103: 0.0,
                 104: 0.0,
                 105: 0.0,
                 106: 0.0,
                 107: 1.0,
                 108: 1.0,
                 109: 0.0,
                 110: 1.0,
                 111: 0.0,
                 112: 0.0,
                 113: 0.0,
                 114: 0.0,
                 115: 0.0,
                 116: 0.0,
                 117: 0.0,
                 118: 0.0,
                 119: 0.0,
                 120: 0.0,
                 121: 0.0,
                 122: 0.0,
                 123: 0.0,
                 124: 1.0,
                 125: 0.0,
                 126: 1.0,
                 127: 0.0,
                 128: 1.0,
                 129: 1.0,
                 130: 0.0,
                 131: 0.0,
                 132: 0.0,
                 133: 0.0,
                 134: 1.0,
                 135: 0.0,
                 136: 0.0,
                 137: 1.0,
                 138: 0.0,
                 139: 0.0,
                 140: 0.0,
                 141: 0.0,
                 142: 1.0,
                 143: 1.0,
                 144: 0.0,
                 145: 0.0,
                 146: 0.0,
                 147: 1.0,
                 148: 0.0,
                 149: 0.0,
                 150: 0.0,
                 151: 0.0,
                 152: 1.0,
                 153: 0.0,
                 154: 0.0,
                 155: 0.0,
                 156: 0.0,
                 157: 1.0,
                 158: 0.0,
                 159: 0.0,
                 160: 0.0,
                 161: 0.0,
                 162: 1.0,
                 163: 0.0,
                 164: 0.0,
                 165: 0.0,
                 166: 1.0,
                 167: 1.0,
                 168: 0.0,
                 169: 0.0,
                 170: 0.0,
                 171: 0.0,
                 172: 0.0,
                 173: 1.0,
                 174: 0.0,
                 175: 0.0,
                 176: 0.0,
                 177: 0.0,
                 178: 0.0,
                 179: 0.0,
                 180: 0.0,
                 181: 0.0,
                 182: 0.0,
                 183: 0.0,
                 184: 1.0,
                 185: 1.0,
                 186: 0.0,
                 187: 1.0,
                 188: 1.0,
                 189: 0.0,
                 190: 0.0,
                 191: 1.0,
                 192: 0.0,
                 193: 1.0,
                 194: 1.0,
                 195: 1.0,
                 196: 1.0,
                 197: 0.0,
                 198: 0.0,
                 199: 1.0,
                 200: 0.0,
                 201: 0.0,
                 202: 0.0,
                 203: 0.0,
                 204: 0.0,
                 205: 1.0,
                 206: 0.0,
                 207: 0.0,
                 208: 1.0,
                 209: 1.0,
                 210: 1.0,
                 211: 0.0,
                 212: 1.0,
                 213: 0.0,
                 214: 0.0,
                 215: 0.0,
                 216: 1.0,
                 217: 1.0,
                 218: 0.0,
                 219: 1.0,
                 220: 0.0,
                 221: 1.0,
                 222: 0.0,
                 223: 0.0,
                 224: 0.0,
                 225: 1.0,
                 226: 0.0,
                 227: 1.0,
                 228: 0.0,
                 229: 0.0,
                 230: 0.0,
                 231: 1.0,
                 232: 0.0,
                 233: 0.0,
                 234: 1.0,
                 235: 0.0,
                 236: 0.0,
                 237: 0.0,
                 238: 1.0,
                 239: 0.0,
                 240: 0.0,
                 241: 0.0,
                 242: 1.0,
                 243: 0.0,
                 244: 0.0,
                 245: 0.0,
                 246: 0.0,
                 247: 0.0,
                 248: 1.0,
                 249: 1.0,
                 250: 0.0,
                 251: 0.0,
                 252: 0.0,
                 253: 0.0,
                 254: 0.0,
                 255: 0.0,
                 256: 1.0,
                 257: 1.0,
                 258: 1.0,
                 259: 1.0,
                 260: 1.0,
                 261: 0.0,
                 262: 1.0,
                 263: 0.0,
                 264: 0.0,
                 265: 0.0,
                 266: 0.0,
                 267: 0.0,
                 268: 1.0,
                 269: 1.0,
                 270: 1.0,
                 271: 0.0,
                 272: 1.0,
                 273: 1.0,
                 274: 0.0,
                 275: 1.0,
                 276: 1.0,
                 277: 0.0,
                 278: 0.0,
                 279: 0.0,
                 280: 1.0,
                 281: 0.0,
                 282: 0.0,
                 283: 0.0,
                 284: 1.0,
                 285: 0.0,
                 286: 0.0,
                 287: 1.0,
                 288: 0.0,
                 289: 1.0,
                 290: 1.0,
                 291: 1.0,
                 292: 1.0,
                 293: 0.0,
                 294: 0.0,
                 295: 0.0,
                 296: 0.0,
                 297: 0.0,
                 298: 0.0,
                 299: 1.0,
                 300: 1.0,
                 301: 1.0,
                 302: 1.0,
                 303: 0.0,
                 304: 1.0,
                 305: 0.0,
                 306: 1.0,
                 307: 1.0,
                 308: 1.0,
                 309: 0.0,
                 310: 1.0,
                 311: 1.0,
                 312: 1.0,
                 313: 0.0,
                 314: 0.0,
                 315: 0.0,
                 316: 1.0,
                 317: 1.0,
                 318: 0.0,
                 319: 1.0,
                 320: 1.0,
                 321: 0.0,
                 322: 0.0,
                 323: 1.0,
                 324: 1.0,
                 325: 0.0,
                 326: 1.0,
                 327: 0.0,
                 328: 1.0,
                 329: 1.0,
                 330: 1.0,
                 331: 1.0,
                 332: 0.0,
                 333: 0.0,
                 334: 0.0,
                 335: 1.0,
                 336: 0.0,
                 337: 0.0,
                 338: 1.0,
                 339: 1.0,
                 340: 0.0,
                 341: 1.0,
                 342: 1.0,
                 343: 0.0,
                 344: 0.0,
                 345: 0.0,
                 346: 1.0,
                 347: 1.0,
                 348: 1.0,
                 349: 1.0,
                 350: 0.0,
                 351: 0.0,
                 352: 0.0,
                 353: 0.0,
                 354: 0.0,
                 355: 0.0,
                 356: 0.0,
                 357: 1.0,
                 358: 0.0,
                 359: 1.0,
                 360: 1.0,
                 361: 0.0,
                 362: 0.0,
                 363: 0.0,
                 364: 0.0,
                 365: 0.0,
                 366: 0.0,
                 367: 1.0,
                 368: 1.0,
                 369: 1.0,
                 370: 1.0,
                 371: 1.0,
                 372: 0.0,
                 373: 0.0,
                 374: 0.0,
                 375: 0.0,
                 376: 1.0,
                 377: 1.0,
                 378: 0.0,
                 379: 0.0,
                 380: 0.0,
                 381: 1.0,
                 382: 1.0,
                 383: 0.0,
                 384: 1.0,
                 385: 0.0,
                 386: 0.0,
                 387: 0.0,
                 388: 1.0,
                 389: 0.0,
                 390: 1.0,
                 391: 1.0,
                 392: 1.0,
                 393: 0.0,
                 394: 1.0,
                 395: 1.0,
                 396: 0.0,
                 397: 0.0,
                 398: 0.0,
                 399: 0.0,
                 400: 1.0,
                 401: 1.0,
                 402: 0.0,
                 403: 0.0,
                 404: 0.0,
                 405: 0.0,
                 406: 0.0,
                 407: 0.0,
                 408: 1.0,
                 409: 0.0,
                 410: 0.0,
                 411: 0.0,
                 412: 0.0,
                 413: 1.0,
                 414: 0.0,
                 415: 1.0,
                 416: 0.0,
                 417: 1.0,
                 418: 1.0,
                 419: 0.0,
                 420: 0.0,
                 421: 0.0,
                 422: 0.0,
                 423: 0.0,
                 424: 0.0,
                 425: 0.0,
                 426: 0.0,
                 427: 1.0,
                 428: 1.0,
                 429: 0.0,
                 430: 1.0,
                 431: 1.0,
                 432: 1.0,
                 433: 1.0,
                 434: 0.0,
                 435: 0.0,
                 436: 1.0,
                 437: 0.0,
                 438: 1.0,
                 439: 0.0,
                 440: 0.0,
                 441: 1.0,
                 442: 0.0,
                 443: 0.0,
                 444: 1.0,
                 445: 1.0,
                 446: 1.0,
                 447: 1.0,
                 448: 1.0,
                 449: 1.0,
                 450: 1.0,
                 451: 0.0,
                 452: 0.0,
                 453: 0.0,
                 454: 1.0,
                 455: 0.0,
                 456: 1.0,
                 457: 0.0,
                 458: 1.0,
                 459: 1.0,
                 460: 0.0,
                 461: 1.0,
                 462: 0.0,
                 463: 0.0,
                 464: 0.0,
                 465: 0.0,
                 466: 0.0,
                 467: 0.0,
                 468: 0.0,
                 469: 0.0,
                 470: 1.0,
                 471: 0.0,
                 472: 0.0,
                 473: 1.0,
                 474: 1.0,
                 475: 0.0,
                 476: 0.0,
                 477: 0.0,
                 478: 0.0,
                 479: 0.0,
                 480: 1.0,
                 481: 0.0,
                 482: 0.0,
                 483: 0.0,
                 484: 1.0,
                 485: 1.0,
                 486: 0.0,
                 487: 1.0,
                 488: 0.0,
                 489: 0.0,
                 490: 1.0,
                 491: 0.0,
                 492: 0.0,
                 493: 0.0,
                 494: 0.0,
                 495: 0.0,
                 496: 0.0,
                 497: 1.0,
                 498: 0.0,
                 499: 0.0,
                 500: 0.0,
                 501: 0.0,
                 502: 0.0,
                 503: 0.0,
                 504: 0.0,
                 505: 1.0,
                 506: 0.0,
                 507: 1.0,
                 508: 1.0,
                 509: 0.0,
                 510: 1.0,
                 511: 1.0,
                 512: 0.0,
                 513: 1.0,
                 514: 1.0,
                 515: 0.0,
                 516: 0.0,
                 517: 1.0,
                 518: 0.0,
                 519: 1.0,
                 520: 0.0,
                 521: 1.0,
                 522: 0.0,
                 523: 0.0,
                 524: 1.0,
                 525: 0.0,
                 526: 0.0,
                 527: 1.0,
                 528: 0.0,
                 529: 0.0,
                 530: 0.0,
                 531: 1.0,
                 532: 0.0,
                 533: 0.0,
                 534: 1.0,
                 535: 0.0,
                 536: 1.0,
                 537: 0.0,
                 538: 1.0,
                 539: 0.0,
                 540: 1.0,
                 541: 1.0,
                 542: 0.0,
                 543: 0.0,
                 544: 1.0,
                 545: 0.0,
                 546: 0.0,
                 547: 1.0,
                 548: 1.0,
                 549: 0.0,
                 550: 1.0,
                 551: 1.0,
                 552: 0.0,
                 553: 0.0,
                 554: 1.0,
                 555: 1.0,
                 556: 0.0,
                 557: 1.0,
                 558: 0.0,
                 559: 1.0,
                 560: 1.0,
                 561: 0.0,
                 562: 0.0,
                 563: 0.0,
                 564: 0.0,
                 565: 0.0,
                 566: 0.0,
                 567: 0.0,
                 568: 0.0,
                 569: 0.0,
                 570: 1.0,
                 571: 1.0,
                 572: 1.0,
                 573: 1.0,
                 574: 1.0,
                 575: 0.0,
                 576: 0.0,
                 577: 1.0,
                 578: 1.0,
                 579: 0.0,
                 580: 1.0,
                 581: 1.0,
                 582: 1.0,
                 583: 0.0,
                 584: 0.0,
                 585: 0.0,
                 586: 1.0,
                 587: 0.0,
                 588: 1.0,
                 589: 0.0,
                 590: 0.0,
                 591: 0.0,
                 592: 1.0,
                 593: 0.0,
                 594: 0.0,
                 595: 0.0,
                 596: 0.0,
                 597: 1.0,
                 598: 0.0,
                 599: 0.0,
                 600: 1.0,
                 601: 1.0,
                 602: 0.0,
                 603: 0.0,
                 604: 0.0,
                 605: 1.0,
                 606: 0.0,
                 607: 0.0,
                 608: 1.0,
                 609: 1.0,
                 610: 1.0,
                 611: 0.0,
                 612: 0.0,
                 613: 1.0,
                 614: 0.0,
                 615: 0.0,
                 616: 1.0,
                 617: 0.0,
                 618: 0.0,
                 619: 1.0,
                 620: 0.0}}

ValueError: Can only compare identically-labeled Series objects